export const DEVEDORES_REQUEST = 'DEVEDORES_REQUEST';
export const DEVEDORES_SUCCESS = 'DEVEDORES_SUCCESS';
export const DEVEDORES_FAILURE = 'DEVEDORES_FAILURE';

export const DIVIDAS_REQUEST = 'DIVIDAS_REQUEST';
export const DIVIDAS_SUCCESS = 'DIVIDAS_SUCCESS';
export const DIVIDAS_FAILURE = 'DIVIDAS_FAILURE';

export const MODAL_UPDATE_STATUS = 'MODAL_UPDATE_STATUS';
export const MODAL_REGISTER_STATUS = 'MODAL_REGISTER_STATUS';

export const SELECT_DEVEDOR = 'SELECT_DEVEDOR';

export const CREATE_DIVIDA_REQUEST = 'CREATE_DIVIDA_REQUEST';
export const CREATE_DIVIDA_SUCCESS = 'CREATE_DIVIDA_SUCCESS';
export const CREATE_DIVIDA_FAILURE = 'CREATE_DIVIDA_FAILURE';

export const GET_PESSOAS_REQUEST = 'GET_PESSOAS_REQUEST';
export const GET_PESSOAS_SUCCESS = 'GET_PESSOAS_SUCCESS';
export const GET_PESSOAS_FAILURE = 'GET_PESSOAS_FAILURE';

export const UPDATE_DIVIDA_REQUEST = 'UPDATE_DIVIDA_REQUEST';
export const UPDATE_DIVIDA_SUCCESS = 'UPDATE_DIVIDA_SUCCESS';
export const UPDATE_DIVIDA_FAILURE = 'UPDATE_DIVIDA_FAILURE';

export const DELETE_DIVIDA_REQUEST = 'DELETE_DIVIDA_REQUEST';
export const DELETE_DIVIDA_SUCCESS = 'DELETE_DIVIDA_SUCCESS';
export const DELETE_DIVIDA_FAILURE = 'DELETE_DIVIDA_FAILURE';
